<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestLego_BL\TestLego_BL.csproj" />
    <ProjectReference Include="..\TestLego_DL\TestLego_DL.csproj" />
  </ItemGroup>

</Project>
