<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LegoTwo_BL\LegoTwo_BL.csproj" />
    <ProjectReference Include="..\LegoTwo_DL\LegoTwo_DL.csproj" />
  </ItemGroup>

</Project>
